apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: autoplayer-secret
  namespace: home
spec:
  encryptedData:
    apiKey: AgAEKfvjMAdtEWZK+1rGrJ8IwU3uLT01cWDSs6IRU5wl+8tfn567m1G3NE9BoTl0CG56gtlbdK5Ls1fWGXfQvstE1oDzu/21WmBGXOCoLQuobCv09Qn3qWLQyJEFMuZJM2om+Yd/XRh61w3YLmgSXIdHLzpG3f/boGhnMZR0iiCyfAtQzWIUODweiU06/P26/3whoMWhMWl2JuPck8RESf9o9h4HsNLJmAnoNB+l6XLBCB50sa/H8QzzkzJl0YQEYvYlW4V3EO3bHREEFezWtFnm4bAozqOEeW+Z7bvNoXWaMRKZD2ihp/VdYa4xQTPVh8IWCp/joydKUmP19OQqu2jdSTpEcLUFSea3p7Ozrt9rVWL2bb91JWw8XaqmgIBhsLMRl31BOdb1a4YjAESY8UtRKcRu6yFnBHSZ3UcqQEKASlsOHN0xPj339t5jgnHAllDRh6YS4715Rh2S78iu54I/Ew1ydfcYemK+cxcPLmDYXiI8xTwN0Yms/H7LQ51nRZTSEtykhV6weXYqndcfLHp2JxHm0r1sghh/Fc3uyPveErsbvMZjTciK+iieUIKw0oxGZgbgK/l4M+g2DH38OBLN48zNB+OjdqX+cgiajtMvI1tcwxZu5jxgkQreDZCkRHd9Wi7zdQ868YNRxN2ex2RK0e4s9yog35l0vUtM0AixK9g+F2VHdizDBh284twgjJGd9piXeykeo/qnwQMvJp2nQ7YC/6M+L4eQZ0NhgtPMn+CirE8=
  template:
    metadata:
      creationTimestamp: null
      name: autoplayer-secret
      namespace: home