apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Chart.Name | lower }}-spotifyd
  labels:
    app: {{ $.Chart.Name | lower }}-spotifyd
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/home/autoplayer"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Chart.Name | lower }}-spotifyd-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: {{ $.Chart.Name | lower }}-spotifyd
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
