apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: services
spec:
  encryptedData:
    password: AgCHxD+ul+Jw/Kkj9ulEJiRocREHeQ731fBznSZ6OPiTS9gd5kCnrWiALzoogqh0U9JGTaapk4SCGYcaQlBrIJo0ssmYqAVPyF1sbwAmiAAmhgyIUasFp1M4Gw4SN/UeDt+PYrf5xr7jfOf7Prt6e1b87vvJRMCR7k26IWdR6ld/5bSGYtSpluGqdBP3/7zOx0cVZp7t6JNmnl+2kiyRQxNHNbGgUCeF3uWa0HZW579iXRaB0IRe49vFGuHxLYf7GZi3g5Aw98c4w8X14/IG1yIYIbfu91YaUwJ0wmmZS37rBjGlRLZ/gEnPH4bAzNaQiVTuu4CjGSxQP18f/PqVB0O3UWTSHRbrNtmJATwtwsvhWjYHBlpTUuPk8dS8P3LhT4yxlw2M0wXY/HH7iTAeTDeEKjDpqfPH9o5qwXGXYLPlUCktPLz7Gi+LPEX9hvs0cBB20h6f2mpjWaRq2k731TVkVshlC3idMkeUlWnJ7nLDXjEcOZiNGnFrGDDPLtXfrll/zZ9h60oA7mFXY1WQM5Du2B+g+juknCNi1azYJeidwPwwyumeB6yM6drUi1SrDe3I3IlspAvA60aeZ/tSLQP1s7fivs4iCZB+pmMZ2HG79uCwHuNouxSmfyZy/HrvxpIanTgv6RGt6elW0vOyMbjgqr6XyfivS04Kzas0tpiysvPWB+fjgtdDftsJN8x10gTswzD9M1w3DqYncHrB2Qr7rP067a22geQ=
    username: AgAhH3rZ2kAVaP4qLMcmF3iudorr0WBla3ZA1i+UIeg4oKGneJ58m+A1hPaUxJLmy/A6PeeJrGNOGdSU+Fk0LZn1J4bVWwXeWEw0X8fONNH6q/Vf4ycImlvHkImoC6MngWh7o4erWk6zrKDSaCUgI4NUWp76EltQHU/X09anSJFOHCyPLnke5zSTvUxmUKuEENEdXCIJbQsNtWmq3r3RgiFL4NCkH2VUecEFn4LH7l6sVxFI7QvYxdQ2Ge9XukjUtHMDqslbC7yZgl6o5vy647IHGuiayaqEk01IXhj//6SnRDWGoPVApibSnaMnN5tc69QPuR2Vo/YXr5QAKSdJeG53aJmyV7dh3CYp19IvdB3cNkSC72haiGcsEYXERbUbQz50L3tZnYvruRDqh7x4b9jB9TzNrC9aSwfw7V+duCVv5yOJ1dTklj7iwWUUfZmo704ERrqiqLSUabOgdSsw/Wzh7fx+nuIMgJ9aa/ZnKh5VOnxSYIRWi2u/tTmRs/PN0iABYyFOOMM4YSfDcbxBmyjo8OUDVkZQFHjRkTnGqKd0Ae8/OMHs9P/uNC8wBYNrcB8uIdQcnpSjdixmrVw0aqFDz71yRxO/SaFR0394UWf6aGbHp7MQ2GKdaTMUav/Ztn7RmT6UVExk4cPgZuZD7ieV/eilO28FuxCNofZ/RiHwRA9C09MehhYhaM3z19OkM47yCesy/kXWlg==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: services
    type: kubernetes.io/basic-auth