apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: default
spec:
  encryptedData:
    password: AgC1f3YgIUzclYngN+kHHDM+cu4ed6vsjsjqYjf1+mJyUNKrcpn1k70snxCBRbv66b8VLADqEdg6pfzaAdIjn/RqcfMSfER6PlZCHs0efQ1j10Q8TndPggTBOCSp+9V3SfkUw6zf30gBxejr+IXGhIWz5pbNllmVNVO+yHxpmWd8EZbbEp7CUFKc9gQ0JE6zHs1S89S/jwKKEblX2T6tSuXF5eUy1fEgvVla2DySRg9UbvoXqoM4W3m5AyjrrwWV3RIimVdSeA7xL/Z0CWXdHmhfr+JagCtfQ9rdsOWC4jxZvCcEKhLC+pIQ6UpgfaARYruAU2jJPYtlpdJDZ2NAxMWsgAASQbnrAylIfC31FIXqjwZzTnrMVr0plW+1XP49cort6TCZAleGfCLHWhu5ywGSV0xlIvc3kE5FzZajzqK5VHta6G8qak0e3wHP1B7U2q42dusP4cuawAB+nim9E0ZeMtzCzZ3IBjgMgcXluDyVdc8FGCV4CSO4GwyYNQrpFC30Ky/87cAhpMapNPzuHYj81m3BkVSie91YEYc1G11dNnczWwQRhJq3TADiAIsvuDIxUDTTHCDrP/Uum7Tu4PuUD/6FvYgn/yN+aPKJRZLiHLn3yXiuFh8dvdb1GGlesSwxtF14eYHqzHS3GeDAg1xwZlsbZ5uEV06ntvpToC3xcR5/CexhjND00/9EdSKY3y4taWcyWCz2448TnyIiZQDXwxm3ghWHc5g=
    username: AgAiU1gmi3dHnSoTgzieaBd1S1L9MqmProVA0Q4eEI+MsN31st6PNKss1PdPYX62hSfGhWiq4CnmdyMJDriKSJIACS6VW1TtxGtYOZN5sMAxI1DsdGShG04CbW8SxVJQkLdeK5HH6PNE7NMxgOl9m5jPMuM8rTHGSQyJM2vlN3MlGW3cRHeJllbWkrhvHXMKWLa0ocnblSQ6OzlCTF8XyEZxD2WJUtANeuIoH9j5iJOoq4+Q+j2syXaW19D6uQ3af3qZMpZZHDfHof4f8jr7S/oSg1rvprN9/9HH3l+1l2CavA1uaXhk1GyCxscq2siWye3xhBY/MIVuMIt5s2+pGwAB2Bob6j+zjf5QiRkGuiSBK12UmlYIcEFD9NrSil2Ctzye6AUoXUxydycw2y3kR9OPN7fogmQWXrI3qrQO69Jn+LSsvc9hmFREkADu/EbSgAtNFhvTvJecsgQCL8Hx15Kh/aYLHesm0DtUa5eowIrGL484PgNyLgbzNES7ILRXZe6FHv8xlfFxuyqT84vgt336kygEUTEn1TzGZ/QjthI0kob2MSCJ1GPPEX4jUBB0ir0iUmlsuv4PFvg/Od5XhKPzOZZ6J18HTLXUv9Ks2tl8FVqGxirhpExQIp2hL5hZvPT5YaFKjfZoB//wFq84Z8wBZa0zMtJ34Q4pXpj/v1XcrUoPuItJQYhm05s6RlNGZk1baJQdXWWjQA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: default
    type: kubernetes.io/basic-auth