apiVersion: v1
name: installers
version: 0.0.1
appVersion: 0.0.1
description: installers
dependencies:
  - name: installers
    version: "0.0.1"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"