spotify-client:
  image:
    pullPolicy: Always
    imagePullSecret: "registry-crazyzone-cred"
  nodeSelector:
    type: autoplayer

  tolerations:
    - key: "type"
      operator: "Equal"
      value: "autoplayer"
      effect: "NoSchedule"

  affinity: {}
  spotifyd:
    labels:
      trigger: "3"
  #Not yet supported, does nothing atm
  cache:
    existingClaim: "autoplayer-spotifyd-claim"
  controller:
    api:
      existsUrl: "https://home.crazyzone.be/audio/spotify/device/"
      startUrl: "https://home.crazyzone.be/audio/spotify/device/"
  secrets:
    existingSecret: "autoplayer-secret"
  securityContext:
    spotifyd:
      privileged: true
      allowPrivilegeEscalation: true