apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secrets
  namespace: home
spec:
  encryptedData:
    password: AgCzW8JSAimPfzWd09MMEXzvLD6UecfBN6mNrHUr2LbYbxAnLg01ehjeD+CU+kIxc5yz/EW7MA05qYBN8AHWrv48nX3OvZNeKT6b4IhQ8uKD+NVRTRVBfuKcxs/WkNs6oNZ4QNMuNroiiXkIyl2GNP6W7ok3v1WiFPIBG9rGitWGAyy6Lx4Kbr7R0/w8oTITeFPUET3nrJSSNsl7IMQ6VBRLocQDHrV4r8QeBHGHJWvflOcpawxrfJp14e3/i34lnmnejiyUeeKwepHns0pgsxqExc1imqgIsTeLjj2lh5Lczz5iprZqh6ZJugCQTP+7Awz3WBSGQxpssVCm/EIZIY15s0RUwOOPRCqrX3Da6i/Z+pRpI3VDMshbqQKO4TjCjl/3A1N2VGb78i0BEDfsddrdY6KJ3vy6+bxANzCQM4UYE2ydAwRA7FutZjrCZfCGA3zHC+FO9flxzSh9EUqk+NhbcdXLDtMPhoZpgvzevwwMhPiyg0whr0+KW65tsMWCbGzRWVVoR6gIEV5yaV2VWyE3S4siVLzxpeJTer6rj2/6xo1wlyGcyCQGC8rw3lanUBcUzV8B8FVNN0YwaqYtwxeNX6lb4LEA+qWLHd/0JImRgkxEKga8G5IetihsrakrDIoZW6Ejy8bmzwOnyCWmdqAdfGoLem5X9QP229Jes3Su/shM5JNr6nwKacvSOD9vIQJladSMNWd10jSOM1m1KaeX7Hfd+3utCEg=
  template:
    metadata:
      creationTimestamp: null
      name: immich-secrets
      namespace: home
    type: Opaque