apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: services
spec:
  encryptedData:
    password: AgBSuoeOv8TCKeBrpXv2YOsEpUDHd94NUxBXdGe3Hy4aJTURAkl1+KO3lWxgEbAm8QiBdTvjYUS1ixbTTswLgDt1TWY74Df7pCU4kHYjIZQ9egVMtClhMk8/MDksAsL5bXDTLqXkw7lWZijHoZ7O7pMn2wVvnzjVUBgblPcOK0wKRYM49i65HYo3UxB087IrqRRORptJREvu2at3WbEq7YJ5TYt84/roqvv6kFQ3+6JyVlmAwlRP81Oggbx7Vi8kRUvmyC+s0BF7EYx4DTQn8hD+aHjmf43Vho0UCjpL0FfeNd4DVBisV+SRU++qiQmrKEV1EIl1inq6jgOEs8PRty9FNVxQyydGRZY+6NKOSZRInWvrea/QX44qhxwKAK976IONjSgA4MveDoDC4bBJsnxnnLlaGF3vkc3C/sAjki9kZbYGEI2x11NRmAxhlYrqcnwvnU6P3CJu9PkTgxLJfOQNP7gYh2A1ocxf036jmBjrJ1ffjFByJXjWxcNycDPKhPZ9r8ijubBKM19uVKYe8ASLSKBYLBHxwTSV/HL8j+FU6A4QYSZFJg9kFHLy8LvaWcMYbUH12Ff7GzR2rjbZz3SyvWFm04O63lGVRb7Qq+4HxgJxMPPBUDJLPE77iRZJEVquyDOy2fZ485ZDNOSOs5N/Gp/dECmfqbS2qVN1wg44QCR62n/R8luDM9RrMyCE5422LNMP1ebo/vEwGLLk65IOXwsf4NNl1Mg=
    username: AgAM9REpMvdWdYchJxwjcO6AKQr9vx8CcsHtYCC9ULfXRJKN1hryN0kjtO59MsoVNWWnNrL0kuCaZhSYGwylZFgBvzF8C2snKcKfieU/yPtt0SG0Q5XCyXpjlUtT+wpF5sagcTyBN6JyiljZurWtBTzgQvYr0ww8wFpRf9/KjLURVzmTfUnyuLGGoQfKS8lStcdio+QKVruuLAfTqawGYcVOOlsy5POJXaxS7cRQoBaTUYekYVNgVUaD08QcxGbJPxkmZApnvs0YYuCo5EUaM12RFrPc0lfbbD+Eczm16V5xqz6aPN0qj/2XXXEfWRQIW9c4b0r0CC+LgaUmI0eevKKFcf0W0arHbo+wThfdRxlgsr4pfWHd4JcxGG61mdXjid+UNbqaFmUt5jlnvy3xN0lu4MrizXB8V5F3bw6dtvlgdGeVCM1ZbAVOxGVEYsRLfYuMeWPCa+rpM2lr2fhNqpK6sQvPVXfN8ZYj45c6RTJXVqU5cpGysTMfvK04x5hnpFSjmQYuiLy7SJZFZGnAwVtmv5l5xQRNl6gDU1pYBmL+WgEyh1IbYtRC22qsqfGUOv8s9K1m36I8ZJrT31ivh2CPQBSR/njqMOWJhKN6p4LmXuPyd70ccioJIfvg0sC12YI9luuWzf+12Tl3p2xQ2PrA/gi+mF/KNTG2+kbUFc4JLRpDNAZS8E/3tpOwUtfQVSflTS32MlAmWw==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: services
    type: kubernetes.io/basic-auth