apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-home-assistant
  labels:
    app: storage-home-assistant
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/home-assistant"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-home-assistant-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: storage-home-assistant
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
