apiVersion: cert-manager.io/v1
kind: ClusterIssuer  # Make this Issuer/ClusterIssuer if you want to serve the whole cluster or not
metadata:
  name: openprovider-acme-issuer
spec:
  acme:
    email: nico.vanlaerebeke@gmail.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory  # Testing usage
    server: https://acme-v02.api.letsencrypt.org/directory  # Production usage
    privateKeySecretRef:
      name: openprovider-issuer-key
    solvers:
      - dns01:
          webhook:
            groupName: cert-manager-webhook-openprovider.crazyzone.be
            solverName: openprovider
            config:
              secret:
                name: openprovider-credentials