apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openprovider-credentials
  namespace: cert-manager
spec:
  encryptedData:
    password: AgBOB1d8wuok+DMMP5F1KS+0CADVD1qIjx0mn4n0sbaX3DCveDo2j4eElxgg8xvAQ6smSPuWSpQcPvj23rl6mbCJMbD0qBZEgVrwlGClzd/ItofzWzv/2NCoUWXdQmLaqSsi0rj9xRc9xv/PgCA7IvlHOpqI3a2+EKYZX1lDoP7yYOLvyznLBe3J0ichXGWYf5XznPCtNfhRzlfQIkXBL26az8gThZSi+DbacpzdDskz02VT3v0EIrYbtEk7jnlf4EoRFmAznV3fUQkBu2wHJdFF2upuRwN3tgq3LNKt0lvMXUru7l4tnFCSLyPtdpEVcz1glgh9N7eVtvb+bqObj9FjT1+8aUB4sF2jH/ZG99L+mdIYcGGtjoyN4Qo+zjA9lyY43lvoRC9yyuP/ega3PIByFR+wGOCLHNaobWjo+2Ww2RtjngphKx3NOIB9bSYWYJeaP2oYWHeTrquDB/55dmRDxPZgRQARZp42xUBiTliIkgb8YnYcp7bzvF/gR4rrDLKjtBmAnTthJ0cELrBnbFRJ/3mmp76/LdvX0AuJJnjqX+jESMLZN2qjHvWimRsSGvN1d3CTVXTcxNEFMPDU98/Am6pae+0jojJ/62IQ4DuScwZAdFDfOfBuKzkPJ2UxWiP7gsT5Ky0CkskAcuTJqeas78cG7HuBkrejy92UiaXFjhBrLFLrrqmimmSa8MALw2dVPvPKoJG+u1cC4nwGL3YFs/KGJO4KVb8=
    username: AgCrpZV+X71XjGlPNP1iAoQNFyZa2tkwAB4o9I5xSADqm9x2+uE6pBUIfIoIoN63i9CF0nL+jJmql+dYFQytOdKYuGUNUv6o1QV7uJZu5BjwzO3Jbepob3Z1VZNeteTw/SuvWozjB1Edhv+wJS+rhQpd3UzvS80d04ygwi4WALr0lNJYqhnbctSENG9zPQ6lXClEmk89BAWHczbWCgvCykoUgxT/ir5wJsZSGtSgybpntFUIZ/QjzVNBRazpYL/YAzpuP5DOpPL5eGHXUiQUSfpw65sj2NTnoGFxGhK0PRtK7PRBkOaEIt0x2oiyBsS36TA5YnzZElT/E6q6urGeDVIcDFW1QhxC7PCmkuVK5IuF/2BmzNoOS9yNM4iNWlML4sZ06nuVhlvOiGtvVrWSzKt/txZruL6gSAjxOzbOlJP7A0ldRkQA1/qBnEw9MCreyOvBFp3D+zMvJWbmNutUQenKpAtWIsCcjQT32igxVoFC3UlNqfp56ACXPjlzyBrDcsvhI+8Nu2ylfW2RlQW3CcR/o+EJK6IC2nC6qGLuvoVEQysEzgUV2yr/HpiZsk5yl1qc9ovsQrbDDAvP89U1LbxVWdz4eFTYaJVVXOervgviDw6lXuMqq9JeVxh7/4q8nGKOwmZsctAnV0OhFItjp8XEi9A3BTbdArERlaXh7DcPnvud2uh2TsGHjZn8e69Nwi838195DOadUPiLD40sRHlcf6/au9qh+L5AIDc=
  template:
    metadata:
      creationTimestamp: null
      name: openprovider-credentials
      namespace: cert-manager
    type: Opaque