apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-crazyzone-be-ssh
  namespace: operations
spec:
  encryptedData:
    gateway-crazyzone-be-key: AgAeRntyrtRAm0Zkrf8hcaUyb4hE8rx+BoF7bs4ByBBLYN3NgBkbWMGmK/5Py3XUEiTJtP+WiP3PnQOCplMOigYzAQ66WtTYaex5Nf8Z7WWq4wTDpbXeVn3j3bv2xCdvzDo/Yz6xVtQRwIScVyrwNF7jDGOeFy+4gmZDoyFcgtTM78trtXvUyHVkfjtx40R2l2aBohigP/X4B1SotOG2KHdONZczWkAwrZ3Pe4DU2p+XPeAAKcPybXO1JslSA06wU9ywcGOcvmPxJCd4QvYsC7QcGVgqQY1pBcXhKXCrot2zIO74GxjkEN1ErJ+fbD+JLrS4sJToRQb7dx2YCaJDB3vW8O7e6PxwbaxQWqz00oIsQ1HTW25RF0NukwUdpjVAoTI/HckzbfPBWGUIJYu8Oio29I9mcOMdWhK2UCl9JMLuiEkGvzgx7FcKutEM6t7zqX3c2Xad6zgzWK/RfKzTmjz8MAoEHi/9IZuCOR6aqYgoFqx5Mzz5lvO4L9zSypYAwgnRRSBfMyFREJCRDMH2ILVP2mgQ4pD2wudlWgxtKdPj6L2uUd+dxb2iGLAcb3RYTWcp07K9mtvXGy640k+w3u+hO1eIPdMLVXqDWNnLVdGhdZ1vBz7a21SP+RjiX17GiZ6TajwBJVfjsrQ0b8MD9nKWplJRaIKh5u+xGDo9UB24U80JI5NoY+FXfnLGVIWbVuz2GanfQewzI0gKMHRVi3Wm6o3bPZEXG78EV18p3uGHMKSO7d+Y1dfScSZ/DapUnQtdmn5pnbbJkQrD8CaWVlkiH8oXBaKSY7c3POEFDpPIVDvGK59IrV8xN7GrVlsZc+aloKCgWS40B3dAKOaniFC1vuEyVtzAVgfp5WLm4HCzLTm71MVBKj2enrOMrkI62GX6CLDsawpVqFglklsn7UoyRfsWS0b1s0RviIgqy9Kgcvc8/iz2d0WEkwfQXaqg+DalxPOUTghRUqTW5vOwnZD66je3gdxQeSetAV8pmh7UWx54K7pae/P2MV+f31vrJAs8EWRpH2O1MVrm2HSrV973e+WzNFe0zAJRTWpcOS+Nf0tpc7Hc/oFznA5cibqfH29id0MRCfaGCXg/APYPmQ+Ikk/FfokeAymzGlndBkBPX1zRcXL5sYydUaoDswd4BdIH2nAQrbk4/TKO3pSDfk+H4XzsgJ6wz+4oGSlK97qwJspkpB5z1DPWDfvcM6+thnpCcefIC9j8Y5jb9FZknSDik3SJrZSQFzFxoMLjQuDDzTTzMg==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-crazyzone-be-ssh
      namespace: operations
    type: Opaque