apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-crazyzone-be-ssh
  namespace: operations
spec:
  encryptedData:
    gateway-crazyzone-be-key: AgCuHOzIVJ+O9FFr8HLQ1IgO58SOZxqeeCcixbTB+LBmTonBdorZiMbK/PhzAkGUDPzZYcPwuN3H/Twkj0GMYxGzKJqL/ufjDQtVUTp+DW0xQxOv3CZ4tR2BBCFqslayhH+MqYRL1F0VYAHJp3HHlHKIUjpxJKHQlaoN4NWow+NWEdS461FtupFBS6jpVMi9arSOydraP8/237WQ/XN8WJJ9lv/OmLuOKCbJTLFDqylfh7ftRMGOZX87/ZR6FNJRWJUB2nUTcguZkfyRX5EXlbX9NOQ5n036JAuPlYxVaKeoUk6wkBgK0Gcs547aULRY6CwBpkpRdt4hqwSYOsRijfWmg2FrzHmf6LNW3qT6Rq4XRkNjoUGo0c17tOwPm1sLrFznKgUp/U+Yf37pjyN5JojXUO2PtJvV4eeJuj8wxHDyULa0FKpRdzRElC+TdyhfAXM0/oPiw2odB2vbfyoddcfDcaBwefV+HvqrCPS+TPoVyhkMvyG5cXPd3qsl04Zk138Oe6YFAdfz/uK/LzIVIZJakA/MGMvt5r8IZVsih9fAjvh64mGWhMHhdml5rvFAkgUvMJASiCMav/mTOvvcl0SfUD8x/ybqaU+kyT8uXMH+jsslNgCD1pvAz2kHrDQVceui7iYdmhth3gOzzi1EqGDbc4pz5zCrN5Jjwzh02RsOBprsVAv5nK1lComHNLqggQHEjhP3XOcX5MufqXVu4CXNkGLq20jcXFdCekgLw8O6YxsKdp15ajv8owq/wO/Em3uAaOPiMjgURUMDRyUNhHebHSVinXCy9wxHdxbqsHKNu0ffTBW6wc9SP5132L7r8GBC93KjLBNpsGObAKtLahSRMWKddRBu5uTt9bQWb3DN7dvZiVXDA/IV2drNvNn7hcY2mLnXtk3aI7NYe10oqMEsK0G/8Pn3V5raXc7xaNurfKLhI0V+QASRNxRCnsQNzq8NHahAm6FVAOkZVmvHJZGFkCt18XKXVNh9PTsOM3BEfzLn1ipf3KwCQHYGuOJjANmSfe5gQhrLpiP5GpboledKUT6FTfRGiQGPdJj8Ilq5sE0HSGYg3IMxcXkwSJU8YFDLqZqTVdNifJik7o72Ci1CZ3mzvDue7K2r17n7qNCTr19DARNgCInFXeEXCPEcsqJWHw6OsitZbelL8CvYRrIDdcCgwvWqROw+UslLXuYXcmslm4J8jEzpU1P8a4Ux1inTc5VqJFWklpL6V9Svg+QvvoHUggsOI7Z0MOY=
  template:
    metadata:
      creationTimestamp: null
      name: gateway-crazyzone-be-ssh
      namespace: operations
    type: Opaque