apiVersion: v1
appVersion: "1.18.2"
description: cert-manager
name: cert-manager
version: 1.18.2
dependencies:
  - name: cert-manager
    repository: "https://charts.jetstack.io"
    version: "v1.18.2"