apiVersion: v1
appVersion: "0.1.5"
description: cert-manager-openprovider-webhook
name: cert-manager
version: 0.1.5
dependencies:
  - name: openprovider-webhook
    repository: "https://git.wukl.net/api/v4/projects/149/packages/helm/master"
    version: 0.1.5