apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: operations
spec:
  encryptedData:
    password: AgBSL1hKYSeD1twcFff/hF2LrjYR16dhfIhGZ17Wd9z46jAg2PUTWP9YkEN5fB/4bpECuBVq8xcAiDyVyX/EVBfZgmKwPf2Kbkfywires3JrTz/8M2DTpklSLzE2AOmkhnEQdkrixus5YUoFQ7gPE6ymfWowo/5i8z4dnlZwyIAUxY0XEf0z5J3QAGzYFLKFH6fSrGsFdKUnCqndytX92oL8HkIpUbPtuCBrRVc6AHHgKbwsWBZUycFRm4GLgMpKd0xXPVY3spx9UDpj71nm9FVC4PLoyOB3Q0O1efVvY599WNXjLca8I+m+FhN3NfIk2hnogpIk3BYXgZkVLwHAB/64EXa+0+JC4H4NXdOcvPl8z6ycVWWY8r/4KXtJAmP9i+fO8v6AQAq6Rs03JVzxbVgnvtUOUfQLzMT2STGZKzUNYLoDUWwLMFY8CehiqTwNu4UtDC08N4VbPdgvnQn//nrBufArE5W1hAlxVa5MTMkAczjreuhwPMLBI3FuDhm5fh94szUF+N2fekcVKE3dET9aLrHkclxuO7qmxkzHcjmsQB1eWMvupi/n5LPGsR2RlObBLit0bBKAVQMeFZ1u28uvJsKQrxGjeJaOJ1R+4B9QoUJyZEOF2pXVkYtNkhtH/S2hOFE8egeDRdfICZqbLwPiG2dG+6mI8yg6VD5GpOCxz0XmAwVjH/tSQ6bAm6J2MX3RfMl7AExNr9N5yEpW7KEDfKxOJbwbtpejYLVxkfc=
    username: AgALuAQfZB8NQismFIGan5AcICYy7mYfYzxx97d8IOoVIs1ygNQlZjoRTKLy+BYgwoTHZNvGS2RCAcEWicU0OQh/sQLETEOEIkm4oDUYvOoJqSTsyjSeZc0opuExTkYVWK1mSi4KYM5rKLBuHyeSSqAt/ZyAaXx0J1NR0ZJVd/9SwymRcJvOfI4vBPOXopQjqGw9tRG/atCNqF7AjYVW5LhmGR1vsH9xPpF+29pgrFte/E+vFbHImfCgt37CuoQN259x5ugXUAT4nxKYrQ8afvG4QvBcrTgo7QKeIyeEhgL/PPjz4FObWc5siN0BBQLSImjNKdPdiACYln2ZPWHH3Lr1KYmDMR/ujS4eIXKw4audm7ELBELQ26gKLSAs9dUBkVVDyr9L4YJPZohzc2uDax8XpIP5S/aUoVLROKVbEP32mO4LZKSFZIncstJfypfkrKNjLUQQkmDoqDJPJliOpGWpbQyP+I8xWvloK7QZwUXGI8wktS28I9mPCfcu1YD8+EHoEy7SYin8EPBl9kF9+1WWqFDsXvJZ+lq90RSUyyOsv7f47rOTeDmSJoPeX3iJt4I5N2xAS74B5BG1vVzftijLRGDcLBZQfRxe7Y+JZwUi9CCqNd8j4A6OdWlE8x1kxjdaDvgF3b79EZloXWaXIYa0epgDbi/Vp1s3OmSGceGqQH07ov6UVzwCEST2q/RLtyqclEPik9virYLSE3XqduHH9SF0vMovQkM=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: operations
    type: Opaque