apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: operations
spec:
  encryptedData:
    password: AgB25HzJSRa1CiWU3b12k/mh2WCtvdNi6JEYDjMuDiGmhw3cSZryzlmOCAfKKA1UAsNgq6ZB5MExiloiJa51zX8P+afI4tfrn10Kg2KZ2kgTtzCvXbGdrnHGM/gsqq74Aryqn3O8EX7GO1E7lcQZHJ1lApBmQm+lUbt5OBsGVSLUs5l1JF9fA1Ma2YkVehZeZi7zMjnnfqCj2x9OHEkdB/6xXpPLmnlE3/0H+ReZJfmwSUvTXYL11VmJkj3CYESTaFiadADh5F+XHeAcMOmigTBRPBVbL0qMvyWgKvMGKWrL7lehR9iFvro6D47rICMRpsigAJy/xNplimVagAuFgMOHoVcDgbjYOG7hhGLF7SB38ZJEo9v16YuR04pIQIk43vz+a4IOjrI6d3lVnUQnkEv3ewV4s1IcP8Sp2JamgPjOhwCfEQ9CTwBPIH8812F7FRJ0snQbv6kDi+UYYDRXuWaeB4VUyH2WL5P1LM9Dl9YeROKNKT034x7iszHdoD9tVVHrVpslII6vvJuAiG7XCuoAd9LzolMWo9TV1h7Gp7h2HStIqp5ObOkJQdN0LENZtfIrTONAwli6uwKq7n1sdRfCitUDmPcQWr+8K++HNriNoFlSlwlXFDCh0rLceEy99fyo73rSkPkLcdbOrvFoZ070ZJl7qjA+UJHYNCHYqSOE35IyUMK62KlfZcOlHKN2HMIhuekSIZRH+Iu+8tTHm418Pv8Uy1TPv8A=
    username: AgAi0FK9+febSc5bbIqq57E2/oGpEBy9W9ICh7dNGcGKP6FFADbu3YdxR3j49Yc1k1N4DncWD7F5HG/w22nfD/anWOiXUK9qaeFExr24HmR9rYEDG5U/a6L2KwfMKcSdmAm5NZplIB+SmD3dAhE6GcNQa/i+EonmKeLVk5b5I8rhRp0FW7f9DnmeLAs5t/V1s9I6tI5Z8jdNce2nYoK+gTNIgePNnDKgITdUJSJlNm+EU8nxuuZElc0kpzYCvOkN/BNobud35xwAdx/ljM3cihVAybpyRjAWxRfqZ/naUDCvh+Ouby5xshoYfHTX+2Mya29UBzxbK0X206BXRYMfN0+1tVczeO1U/gfKR6/qBMPFLIV0T7hVxOPqo7cdQxd2gOYjodq+ySmDE1s+qYbSWGUbVoKIrwIcXVK6qEcoY7JoHdHG0IgMmfWL/JcNsyGVdUitkwu/FlYMhr5Eu55GM3d3qzWs148Aj2qcVH8NvVC7psnExaX4H2LixJQy8iXhXOB7yl37pNUkg8SMmbBG6bmULGk+IPQjnSjHSpIjOMi2CaiZ8AHfr0FvhMS7RjkcXeCMmv7Xv82Rk+ll1oa/Pyd/rtb7rlf44jjmnOHcesGIE/1vKMPwbs0IckelUCPeyCSQHoWmR1VDmILkfZNzTWYS9YYYcRUQsVW661ildGzR3SP744we4FHPm+pN22c1xqEL7iiH6Pu1eB2eOFtlOsum56yIwUSO15gm0FTwVmA=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: operations
    type: Opaque