apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: operations
spec:
  encryptedData:
    password: AgDAyI3zChn23MthD5S8IXz9pzG8P99C/BlSTdsBpDoC+gYy0pjEv6R6/q7n29oDVFWd7VyyrKzfZ9L3CxwDgM+w8ykrh8qDNew9bbCqcBwSuoTZ0d43S++ZMDKdXYiw63EAWERpIY+yDSIPATIEgZ7Q+bw/l/DJHgfM+lD2EkUuuFtCas0qYXOzAutYP/50D5cX/yMsJdagxZHE9GirSLCw/q79vCu4l9XAv5v0ginlhWCDQFoYS7v+3+KxWWHdK2i8+r+VBcIw4M2egnXUl162cw63/BjBkcKLIWFTsGU+Sxx8pReGM9YSXZD1WMFWE5/VVrOmDongUujXBbzUzGeYqF7IfOOioXm0Kvw3vojGBE5An+hCY7xUh2u3n24BInlAa7ZkJm+QvkqulbpBvsarNOps4Czixe3ZNEH4GjkLktFyc0VJxHm2OQBWhYwZjuj6TIhxrZIw0yxuCjKO4TNxwR2WBMY1WEY/FxNxFCFZ1CWRGp0RDppWhDWC4lg27F6kby3JoWqfm8HHWpCftSXdT1qpXNDOxZfqkgWwBR+CctQT1Z0INdHoi98OC267mvjGzmRxPb3/pWptW9w4Oo54RmNVRVY4CDo2rsVoTyYM9pw/dyhEtBXcKBAZwvqDH1u5NHGgPDLC/QPWji1mHqN5lzLP1JPhoF9+tfmuiOZM8QEIsiQVBhI3EFyfyFfAEI8A8qSeKDmUt1E9zVcahdaTj/0xtVu+iFE=
    username: AgARV4hQalZG4gzXTQoBhi8UG+l/ZyxZZAKZSZiPn8pJSy1NtRVf/Ua3+KkhSzsmnRsJZhALpdyYZkq6ulNc6o+XZZjguKVGIT8z8bsXAPPwvoHyUpvKVEt71DZsPPox5n/VzPNLLNjKrxjzdbKR0bAO30RhIcwwCeV8YNVg8Rw+zCbsOx1jolcexE0a1gPXlZ+4c78iUfm2/k6/wwVXBJAPKSYJrGDi0uveaEUIF2+0UbDGK7d550VIiDusxkUNKcn/c7vQe81tk1cfdJ5Ih8PX4ShO+reEnrzEs2XRfz275FpF2vkyrE6q/QBoT1VOLQC9sCeWN9HKmWJRLtbxN9gDrs4peJ3MbDRG04KbIe9FDdKaIzpz91+6ZARbUGLMES/qcG4VmTE/ceEd5P/eqDPToppB5Yv4PMwZeYENP5VFRiCBLYMrqSjil2D0Sd/vETb8DTIjjoAoVrC1cw1FG0a7teFpcdBP1AjN5Im3BWA34c53yDZMma5ct+qKU64WB9f6XKwcx6MrP6UlBBgTl/PC0WxLGq49TAjnaufg7g0lhisld3ZtwCjq/lxJ18m6DI+orJpjhfb7iSUBTDRJmWYuvyuXjflpvmuvQbegiFYAstBjgSV1vMEu4m4jW0xJWthKFyv/SMMO2pq95wanGr0VMtpOJDmRvU1bZy9sAh3CH2yoL3OPaHNySnk/IWUNqZcXPnhVlRbD5yta2mIU
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: operations
    type: Opaque