apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-passwd
  namespace: home
spec:
  encryptedData:
    htpasswd: AgB2Ni6T3OHeyTZRxUW+BMU+/9ya267f3cMTtpjqHCiOaW6rHIV+akGuUtaTcqTpZZ698GemnyLlRSW4jj5ES+QI+4GwagHmjwOCIdHkaTnEoIzNedRyQLiiOZg4h8+lMDcTcyzzQX5YGeu0QVH6f+uK+bRnCyRZa32NhXdw2tRTWPcHyRupx2rppPuV/c2zNEOWOQo1W7IJGGmYYH3zssBKIuXNKkEFGWUr7GDKl1c1bf3gB98ip7djlFIcVnayDwCvxenWHGrRCvchGAXFp9jecHZc81HetPoNWKVeLSV87TDBqqWfkxommYJ/jiWRO9nWsyUBvUD277kcuJKEO0ZE3T1MddBR+ruFYnaF4z3uwLRUZ3UhLemN7Otl7FOVCg2h/GAzz1FDvUAWco3/DpoU0HH2sZPxgLU0wJPZmD6402t0tk0dYoO1apnqKgehvs+8NpDJe5S/sv4Y4hH/FK6dPhnZIhIegb3CM4D3HVwBTtWVpvof0x6MWANpoDfw7DGt7pQmJVYdq1qx+rlPKDXDTPZrfi1Qh1mSxA3RTK08eHUa63cegCG6tsmtxGFqTF52Q6PwQANUS1KxSm4D/wcovH64D7Y1hwDcIYt+u+drIavyD8/COyPG3x/ImLW6/3sv6yMxAZ+uzLA+60rMVIrHG9P0+qWSxP/sOG3Nt/Y00fzug4wZkt2PW4N1z3o23R+od5DOMq0pBTDTb79asdZl+bW5zp7YcyOnMisDQsHsYTq7k9VbrO9G9xZcvrdJOnAmcHxsjK0WuHivbtS3KJdzT/M=
  template:
    metadata:
      creationTimestamp: null
      name: secret-passwd
      namespace: home