apiVersion: v1
kind: PersistentVolume
metadata:
  name: crazy-store
  labels:
    app: crazy-store
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/store/android"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crazy-store-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: crazy-store
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem