apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-secret
  namespace: power
spec:
  encryptedData:
    SPOTIFY_CLIENT_ID: AgC6Na/9wIJu81FC/vWtWWsdd4U3ruxryeLRozCIaj1G92KEUEwmZiGpN9py29GMT/tbybFfy7RP041RoF4HW06hzAGoCt8fQULWttUzfJ3AvaUYdn23lCxqDqCJ14UB700L4rj/pnX25m1XcUadqkHdOaVVRMNLlfVUdtnUeJLseNybqZ1Ac5PLupwi3cDRSOmUPovFj6o4tCGhvqA0+WO2HeHZ1AlsLccTj1/9a46FnXdbF4Zn0q+VMNVxLZb9TmEeTbxinkfCek+KP97mhCqxcBK4fggGzl7MKdaKAaTs8soXNCPHtfxN8r8F8y9CEdLqqVay8ibPtIFk3zeiKL7IUh3QHGiAXhl86r9SghkkvlZ4vYiuUkGX16fTrb47r5VQd54fEfic5/riZIS2GiFoeXK8qasUrgprbm0fw/LhRKbSvz36uh60M0PcDG5ae6/yaJDOBvJCgpUDqdBdbtH3w75vesxYOtLQgox2il4FzEtlHrO7u747LWDqsQ7m0+RvUrFc0GdLBP/LR4kWsOtk+5xm9Uix4QOIfq1UfMi5CuJv2Um6jJ999Nu1BmtfLU4TZBSHkA+ALrBRBBr0hA1JwXWALLvzrqAH4YvvOrd3u7FbAGvTdYs1I7X2sX1JA6CQ+vlnYCQYQyPQxSllif9m9kyZIsa84g+8n6hFGOZbi62FbVLCFOB48CpUg/jwmfCTfIyFzwFfKS+uqLplDkUGP/81BosOx6w7sa0AeVqpdQ==
    SPOTIFY_CLIENT_SECRET: AgC412JeZEww00ubVXyA5gGizXdvNqn+iSBX6R6jkM+ek9n4MVrGEfVRKICSK27QE5H0oGUtM0uDtd/QFuCNndvFf3GM6zeYft2kJLwLJBXFAIpcaatkgAruzLxy1xCYc80xr7LDEw+Mxk+UihaXBxCyh9RkLSSf/nRzrlSYQSJJnebFdjb9ShvgFF+KFvcbAG4TY5bpfxqQwFPG23Ck+vDQ5oNnt36OMkETdTwVeoAnNcdRAArOcsVUr020f4s5ztZ187gpqi3lFjNfuZldFaOfFiLKqWP1dtED3VgOVaFgInMS/JaF0sQk65y2jixdTaVWoFJjRTQ9cvaw2ftjfvSqnv+HQct1JThCwpQseSoii/7+jGHDOrb3U6UUiVKORiHV2tlW2v6+9zXD8/W/gPlJ6AujOdJR3DA85lryMJNlvEJh0nkioynkS83QOLlOL2si9Hd5mSAlh0AtbwvDw5Osn5cJqYNoNsZuWtXvVXjetIFZYfyCveCOvqqWQwlg+EwsBv0cyKRFFoOlMzYp1KbtMYwzEceTHwXY2Tj6cbHaACXqx5LgCmZxhO8JOCwVk3f+Z5YAc8vp4WO/tlWWOV9nBoFK3l557r2pbaxp/SOJ4PLBt0oNhvo9DXqkh3M0B0xPbgV6Jj8vfi1M3SGAQhIE0S3t7kwiHr64tR+Lv1Z4Dh4WgzBdteqyKWWxnKNXdXWVuwIhcX3LaE2q1noH6OKlGpoX/fRJx1DkfyrVwIw/xg==
  template:
    metadata:
      creationTimestamp: null
      name: home-secret
      namespace: power
    type: Opaque