apiVersion: v2
name: crazy-home
version: 1.0.1
appVersion: 1.0.1
description: Application to communicate with the MQTT and plugwise devices
dependencies:
  - name: home
    version: "1.0.1"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"