apiVersion: v2
name: crazy-home
version: 2.1.0
appVersion: 2.1.0
description: Application to communicate with the MQTT and plugwise devices
dependencies:
  - name: home
    version: "2.1.0"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"