home:
  global:
    imagePullPolicy: Always
    existingRegistrySecret: registry-crazyzone-cred
  plugwise:
    enabled: true
    device:
      path: /dev/ttyUSB0
  ingress:
    enabled: true
    labels:
      trigger: "3"
    hosts: 
    - host: home.crazyzone.be
      paths:
      - path: /
        pathType: Prefix        
    tls:
    - hosts:
      - home.crazyzone.be
      secretName: crazyzone-be-tls
  mqtt:
    persistence:
      enabled: true
      existingClaim: "crazy-home-storage-api-claim"    
  mosquitto:
    persistence:
      enabled: true
      existingClaim: "crazy-home-storage-mosquitto-claim"
    service:
      type: LoadBalancer
  zigbee2mqtt:
    zigbee2mqtt:
      serial:
        port: "tcp://zigbee.crazyzone.be:6638"
      frontend:
        enabled: true
    statefulset:
      storage:
        enabled: true
        size: 1Gi
        storageClassName: "standard"
        existingVolume: "crazy-home-storage-zigbee2mqtt"
  spotify:
    existingSecret: home-secret