apiVersion: v1
name: PostgreSQL-2
version: 0.26.1
appVersion: 0.26.1
description: PostgreSQL
dependencies:
  # CNPG Operator (CRDs + controller)
  - name: cloudnative-pg
    version: "0.26.1"
    repository: "https://cloudnative-pg.github.io/charts"

  # CNPG Cluster (creates a Cluster CR -> actual Postgres pods)
  - name: cluster
    version: "0.5.0"
    repository: "https://cloudnative-pg.github.io/charts"