apiVersion: v1
name: power-reader
version: 0.0.14
appVersion: 0.0.14
description: Application that reads data from the P1 serial port
dependencies:
  - name: power-reader
    version: "0.0.14"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"