apiVersion: v1
name: wekan
version: 8.17.0
appVersion: 8.17.0
description: Experience efficient task management with WeKan - the Open-Source, customizable, and privacy-focused kanban.
dependencies:
  - name: wekan
    version: "8.17.0"
    repository: "https://wekan.github.io/charts/"