apiVersion: v1
name: crazy-store
version: 0.0.3
appVersion: 0.0.3
description: Crazy's Android Store
dependencies:
  - name: crazy-store
    version: "0.0.3"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"