apiVersion: v1
name: crazy-store
version: 0.0.5
appVersion: 0.0.5
description: Crazy's Android Store
dependencies:
  - name: crazy-store
    version: "0.0.5"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"